on: [push]

name: CI

jobs:
  build_and_test:
    name: CI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: setup rust stable
      run: curl https://sh.rustup.rs -sSf | sh -s -- -y
          
    - name: unit tests  
      run: cargo build --release && cargo test --all --release   
        
    - name: runtime test
      run: |
            ./target/release/server &
            ./target/debug/server &
            a=$(curl 127.0.0.1:3030)
            if [[ "$a" = "\"Blocked\"" ]]; then 
                exit 1
            fi
            ./target/debug/server &
            a=$(curl 127.0.0.1:3030)
            if [[ "$a" = "\"Blocked\"" ]]; then 
                exit 1
            fi
            ./target/debug/server &
            a=$(curl 127.0.0.1:3030)
            if [[ "$a" = "\"Blocked\"" ]]; then 
                exit 1
            fi
            ./target/debug/server &
            a=$(curl 127.0.0.1:3030)
            if [[ "$a" = "\"Not Blocked\"" ]]; then 
                exit 1
            fi
